services:
  ah_ros2_urdf_viewer:
    container_name: ah_ros2_urdf_viewer
    working_dir: /
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    network_mode: host
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock

